/* Generated by Yosys 0.33 (git sha1 2584903a060, clang 14.0.0 -fPIC -Os) */

(* src = "test.v:1.1-11.10" *)
module test(A, B, C, D, E);
  (* src = "test.v:4.11-4.12" *)
  input A;
  wire A;
  (* src = "test.v:4.14-4.15" *)
  input B;
  wire B;
  (* src = "test.v:4.17-4.18" *)
  input C;
  wire C;
  (* src = "test.v:3.11-3.12" *)
  output D;
  wire D;
  (* src = "test.v:3.14-3.15" *)
  output E;
  wire E;
  (* src = "test.v:5.11-5.13" *)
  wire w1;
  assign E = ~(* src = "test.v:0.0-0.0" *) C;
  assign w1 = A &(* src = "test.v:7.8-7.20" *)  B;
  assign D = w1 |(* src = "test.v:9.8-9.20" *)  E;
endmodule
